[package]
name = "macos-sucks"
version = "0.1.0"
edition = "2024"

[dependencies]
envie = "0.2.1"
gurtlib = "0.1.0"
serde_json = "1.0.145"
tokio = "1.48.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
